// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"database/sql"
)

type Author struct {
	ID        int64
	Email     string
	CreatedAt string
	UpdatedAt string
}

type Comment struct {
	ID        int64
	Body      string
	EntryID   int64
	AuthorID  int64
	CreatedAt string
	UpdatedAt string
}

type Entry struct {
	ID        int64
	Title     string
	Body      sql.NullString
	CreatedAt string
	UpdatedAt string
	AuthorID  int64
}
